apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turnis.fullname" . }}
  labels:
    {{- include "turnis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.slack.botToken }}
  TURNIS_SLACK_BOT_TOKEN: {{ .Values.slack.botToken | quote }}
  {{- end }}
  {{- if .Values.slack.appToken }}
  TURNIS_SLACK_APP_TOKEN: {{ .Values.slack.appToken | quote }}
  {{- end }}
  {{- if .Values.slack.signingSecret }}
  TURNIS_SLACK_SIGNING_SECRET: {{ .Values.slack.signingSecret | quote }}
  {{- end }}
  {{- if .Values.email.username }}
  TURNIS_EMAIL_USERNAME: {{ .Values.email.username | quote }}
  {{- end }}
  {{- if .Values.email.password }}
  TURNIS_EMAIL_PASSWORD: {{ .Values.email.password | quote }}
  {{- end }}
  {{- if .Values.twilio.accountSid }}
  TURNIS_TWILIO_ACCOUNT_SID: {{ .Values.twilio.accountSid | quote }}
  {{- end }}
  {{- if .Values.twilio.authToken }}
  TURNIS_TWILIO_AUTH_TOKEN: {{ .Values.twilio.authToken | quote }}
  {{- end }}
  {{- if .Values.twilio.fromNumber }}
  TURNIS_TWILIO_FROM_NUMBER: {{ .Values.twilio.fromNumber | quote }}
  {{- end }}
